// This file is auto-generated by scripts/update-backend-config.js.
// Do not edit it manually.
export const BACKEND_IP = 'https://georgie-scapulohumeral-kyle.ngrok-free.dev';
export const BACKEND_PORT = '8000';
export const API_BASE_URL = 'https://georgie-scapulohumeral-kyle.ngrok-free.dev';
