export const eventToParams = (item: any) => ({
  id: item.id?.toString(),
  title: item.title,
  description: item.description,
  hostUsername: item.hostUsername,
  locationName: item.locationName,
  latitude: item.latitude?.toString(),
  longitude: item.longitude?.toString(),
  startAt: item.startAt,
  startLabel: item.startLabel,
  price: item.price?.toString(),
  currency: item.currency,
  imageUrl: item.imageUrl,
  eventCategory: item.eventCategory,
  maxAttendees: item.maxAttendees?.toString(),
  ticketsSold: item.ticketsSold?.toString(),
  canBook: item.canBook?.toString(),
  mapUrl: item.mapUrl,
  ticketType: item.ticketType || 'Free',
  ticketTiers: JSON.stringify(item.ticketTiers || []),
  mediaUrls: JSON.stringify((item.mediaAssets || []).map((m: any) => m.file_url || m.fileUrl).filter(Boolean)),
});
